#!/usr/bin/env python3
"""Gera os 20 pedidos U01–U20 ao ChatGPT web (Balcão, seção U) conforme a skill pedidos-chatgpt-balcao:
kit local, run no agenthub (materiais de texto pelo túnel), pedido no Balcão com run_id. Uso: gerar.py [--publicar]"""
import json, os, re, subprocess, sys, shutil
from pathlib import Path
R = Path(__file__).resolve().parents[1]; K = R / 'pedidos-chatgpt'
CTX = """CONTEXTO
Projeto independente, educacional e não afiliado: reconstrução forense digital do Richard Mille RM UP-01 Ferrari e do calibre RMUP-01 a partir de fontes públicas (repositório aberto github.com/pedropasinn/rmup01-digital-twin). Regra central: toda afirmação carrega classe de evidência — A primária (fabricante, patente, documento oficial), B observada (visível em foto/vídeo), C medida (metrologia de imagem), D inferida (imposta por geometria/cinemática), E hipótese, F placeholder — e fonte com URL real. Nunca apresentar C, D, E ou F como A. Âncoras já conhecidas a confirmar: relógio 1,75 mm; calibre 41,45 × 28,85 × 1,18 mm; corda manual; seletor W/H; ~45 h; 23 rubis; balanço titânio grau 5 de três braços e seis massas; 3 mg·cm²; ângulo de levantamento 54°; 28 800 A/h; espiral AK 3; Kif; barrilete ~6 h/volta; platina e pontes em titânio grau 5; escape ultraplano patenteado sem dart/guard pin e safety roller (EP3754433A1 / CH716337A1 / US11550262B2, Giulio Papi, prioridade 2019); cristais 0,45 mm (horas) e 0,20/0,30 mm (balanço); 13 parafusos spline; 1 atm; > 6 000 h de desenvolvimento; tolerâncias de 1 μm citadas; involuta 20° citada para winding-barrel e pinhão da terceira.
REGRAS
1. Só fontes públicas obtidas legitimamente; paywall se registra (título, veículo, URL), não se contorna; nada vazado.
2. Toda fonte com: título original, autor, veículo, data, URL (que exista), idioma, tipo; toda afirmação com classe A–F e fonte. Nunca inventar URL, número, autor ou citação. Marcar hipótese como hipótese.
3. Desenhos de patente não são escala: nunca extrair medidas deles.
4. Português brasileiro; tabelas; resumos próprios (não copie textos longos); traduções só para entendimento, preservando o original.
5. Entrega: um único zip <ID>-entrega.zip com a estrutura pedida, um LEIA-ME.md de meia página e um fontes.csv (source_id local, title, author, outlet, date, url, language, type, rights, claims_supported, notes) e um claims.csv (claim_id local, subsystem, statement, evidence_class, sources, parameter, notes).
"""
P = [
 ('U01','Dossiê oficial Richard Mille: páginas, press kit, especificações','GPT-6 Pro',"""TAREFA — Reunir tudo o que a Richard Mille (e a Ferrari) publicou sobre o RM UP-01: página do modelo, press release, fichas técnicas, PDFs, vídeos oficiais, galerias, comunicados, catálogos, páginas históricas e versões em outros idiomas (en, fr, de, it, ja, zh, es, pt). Para cada âncora do contexto: o trecho literal em que ela aparece, a página e o idioma, ou a marca "não encontrada em fonte primária". Entregar `oficial/dossie.md` (por fonte: o que diz, com trechos curtos), `oficial/ancoras.csv` (âncora, valor, trecho, URL, idioma, classe A ou "não confirmada"), `oficial/midia.csv` (imagens/vídeos oficiais: URL, resolução aparente, o que mostram), fontes.csv, claims.csv."""),
 ('U02','Linha do tempo do RM UP-01 e do calibre RMUP-01','GPT-5.6 Pro',"""TAREFA — Reconstruir a cronologia pública: anúncio, lançamento, edições, tiragem, preço de lançamento, prêmios, aparições (feiras, leilões), evolução da comunicação (o que a marca disse em cada momento), o programa de desenvolvimento (6 000 h, protótipos, parceria Audemars Piguet Le Locle/APRP) e o que a Ferrari publicou. Entregar `cronologia/linha-do-tempo.md` (data, evento, fonte, classe), `cronologia/pessoas.csv` (quem falou o quê: Richard Mille, Giulio Papi, Salvador Arbona, engenheiros, jornalistas), fontes.csv, claims.csv."""),
 ('U03','Patente EP3754433A1: leitura comentada das reivindicações e figuras','GPT-6 Pro',"""TAREFA — Ler a patente EP3754433A1 (e a correspondente US11550262B2 e CH716337A1) no Espacenet/Google Patents e entregar `patente/leitura.md`: (1) o problema que ela declara resolver; (2) reivindicações independentes e dependentes reescritas em linguagem própria, uma a uma; (3) para cada figura, o que mostra (peças, referências numéricas, estados do escape) sem extrair nenhuma medida; (4) o que muda em relação ao escape de alavanca suíça convencional (guard pin, safety roller, dart, chifres do garfo, bancos); (5) o que a patente NÃO diz (dimensões, materiais, contagens); (6) glossário dos termos da patente pt/en/fr. Mais `patente/reivindicacoes.csv` (nº, tipo, resumo, elementos) e `patente/figuras.csv`. Classe A para o que está no texto; D para inferências suas, marcadas."""),
 ('U04','Árvore de patentes de Giulio Papi / APRP / AP Le Locle sobre escapes e ultraplanos','GPT-6 Pro',"""TAREFA — Levantar, em Espacenet, Google Patents, WIPO e Swissreg, a família da EP3754433A1 e as patentes relacionadas com inventor Giulio Papi ou titular Audemars Piguet/APRP/Renaud & Papi que tratem de escapes, ultraplanos, barriletes, seletores de função e cristais. Entregar `patentes/arvore.md` (famílias, prioridades, titulares, status legal, CPC, relação com o RM UP-01: certa / provável / apenas temática), `patentes/patentes.csv` (número, título, prioridade, publicação, titular, inventores, status, CPC, URL, o que ensina em uma linha) e uma lista das que merecem leitura completa. Sem medidas de desenhos."""),
 ('U05','Patentes e registros da Richard Mille sobre caixa e movimento ultraplanos','GPT-5.6 Pro',"""TAREFA — Buscar patentes, modelos de utilidade e registros de desenho industrial da Richard Mille (e parceiros) que possam corresponder ao RM UP-01: caixa monobloco/caseband, fixação por parafusos spline, integração caixa-movimento para rigidez, cristais finos, seletor de função, coroa/comandos frontais. Entregar `patentes-rm/lista.csv` e `patentes-rm/analise.md` (o que cada uma ensina; grau de relação com o RM UP-01), com URLs de bases oficiais. Sem medidas de desenhos."""),
 ('U06','Imprensa técnica em inglês: resumos por subsistema','GPT-5.6 Pro',"""TAREFA — Catalogar os artigos em inglês com conteúdo técnico ou fotos de primeira mão sobre o RM UP-01 (Hodinkee, SJX/Watches by SJX, Monochrome, Revolution, WatchTime, Europa Star, FT/HTSI, Fratello, Quill & Pad, TimeZone, A Blog to Watch, etc.). Para cada um: o que revela por subsistema (caixa, cristais, platina/pontes, barrilete, corda, seletor W/H, trem, escape, balanço/espiral, indicação, rubis, choque, fixações), quais fotos únicas contém (descrição, não o arquivo), qualidade e confiabilidade justificadas, paywall sim/não. Entregar `imprensa-en/indice.md`, `imprensa-en/por-subsistema.md` (o melhor material por subsistema), fontes.csv, claims.csv (só B/D com fonte)."""),
 ('U07','Imprensa em francês, alemão e italiano','GPT-5.6 Pro',"""TAREFA — O mesmo levantamento do pedido de imprensa em inglês, agora em francês (Le Temps, Montres Passion, Watchonista, Journal Suisse d'Horlogerie, GMT Magazine), alemão (Uhren-Kosmos, Watchtime.net, Chronos, NZZ) e italiano (Orologi & Passioni, Il Giornale degli Orologi, Chrono24 IT). Entregar `imprensa-fr-de-it/indice.md` (título original + tradução do título, veículo, data, URL, idioma, o que revela por subsistema, fotos únicas, confiabilidade), `imprensa-fr-de-it/por-subsistema.md`, fontes.csv, claims.csv."""),
 ('U08','Imprensa em japonês, chinês, espanhol e português','GPT-5.6 Pro',"""TAREFA — O mesmo levantamento em japonês (Hodinkee Japan, webChronos, Gressive), chinês (Xbiao, WatchsHK, mídia de HK/TW), espanhol (Revista Relojes, Horas y Minutos, Watchtime ES) e português (Watch Time Brasil, Relógios & Canetas). Entregar `imprensa-ja-zh-es-pt/indice.md` (título original + tradução, veículo, data, URL, idioma, o que revela, fotos únicas, confiabilidade), `por-subsistema.md`, fontes.csv, claims.csv."""),
 ('U09','Entrevistas: Giulio Papi, Richard Mille, Salvador Arbona e engenheiros','GPT-5.6 Pro',"""TAREFA — Localizar entrevistas, palestras, podcasts e vídeos (com transcrição pública ou legendas) em que Giulio Papi, Richard Mille, Salvador Arbona, Julien Boillat ou outros envolvidos falem do RM UP-01, do calibre RMUP-01, do escape ultraplano, do balanço, da parceria com a Ferrari ou dos desafios de espessura. Entregar `entrevistas/catalogo.csv` (quem, veículo, data, URL, idioma, formato, minuto/trecho relevante), `entrevistas/trechos.md` (citações curtas com atribuição e URL; classe A quando é a pessoa responsável falando), fontes.csv, claims.csv."""),
 ('U10','Anatomia comparada dos ultraplanos: Piaget, Bulgari, AP, Vacheron, Jaeger, Richard Mille','GPT-6 Pro',"""TAREFA — Tabela dimensional e arquitetural, com fontes, dos calibres/relógios ultraplanos de referência: Piaget 9P e 900P/910P, Bulgari Octo Finissimo Ultra (BVL 180) e BVL 138, Audemars Piguet 2003 e RD#3, Vacheron 1003, Jaeger-LeCoultre 849/145, Jean Lassale 1.2, Concord Delirium, Richard Mille RM 67-01 e RM UP-01. Colunas: ano, dimensões do movimento e do relógio, frequência, reserva, rubis, tipo de escape, barrilete (rotação rápida? peripheral?), balanço, como resolveram a espessura (arquitetura espalhada, caixa como platina, cristais finos). Entregar `comparado/tabela.csv`, `comparado/analise.md` (o que o RM UP-01 herda e o que é inédito), fontes.csv."""),
 ('U11','Escape de alavanca suíça como baseline e o que o RMUP-01 elimina','GPT-6 Pro',"""TAREFA — Escrever um dossiê técnico e didático sobre o escape de alavanca suíça convencional: geometria (roda, âncora, paletas de entrada/saída, garfo, chifres, dart/guard pin, roller de impulso e roller de segurança, bancos), o ciclo (lock, unlock, impulse, drop, draw, run to banking), a função de segurança contra overbanking, alturas típicas envolvidas, e depois uma seção "o que a patente EP3754433A1 remove e substitui" (com a leitura do texto da patente, sem medidas). Entregar `escape/baseline.md` (com figuras próprias descritas em texto ou SVG simples gerado por você), `escape/comparacao.md`, `escape/glossario.csv`, fontes (Daniels, de Carle, Reymondin, patentes) com referências completas."""),
 ('U12','Balanço de três braços: faixas dimensionais a partir de 3 mg·cm², 4 Hz e titânio grau 5','GPT-6 Pro',"""TAREFA — Cálculo inverso documentado: dado o momento de inércia publicado de 3 mg·cm², 4 Hz, titânio grau 5 (densidade e módulo com fonte), três braços e seis massas de regulagem, produzir faixas plausíveis de diâmetro do aro, seção do aro, massa total e rigidez da espiral (k = I·(2πf)²), com cada hipótese marcada (E) e o cálculo mostrado (A sobre E). Comparar com balanços de outros ultraplanos (fontes). Entregar `balanco/calculo.md`, `balanco/balanco.py` (stdlib; saída JSON; varredura de hipóteses), `balanco/faixas.csv`, fontes.csv, claims.csv (classes D/E)."""),
 ('U13','Barrilete de rotação rápida e trem: restrições, razões e método do solver','GPT-6 Pro',"""TAREFA — A partir de ~45 h de reserva, ~6 h por volta do barrilete, 4 Hz e indicação de horas e minutos: (1) deduzir o número de voltas úteis da mola e a razão total barrilete → escape; (2) enumerar arquiteturas de trem compatíveis (número de estágios, faixas de dentes por estágio com módulos plausíveis para um calibre de 1,18 mm, sentido de rotação), como conjunto de candidatos, sem escolher "porque parece bom"; (3) especificar um solver combinatório em Python (stdlib) que recebe centros medidos, diâmetros observados e as restrições, e devolve candidatos com resíduos; entregar o solver funcionando com dados de exemplo marcados como exemplo. Entregar `trem/restricoes.md`, `trem/candidatos.csv`, `trem/gear_search.py`, fontes.csv, claims.csv (D/E)."""),
 ('U14','Caixa em titânio grau 5, 13 parafusos spline e cristais de 0,20–0,45 mm','GPT-5.6 Pro',"""TAREFA — Dossiê sobre a caixa e os cristais do RM UP-01: o que a marca publica (materiais, parafusos, resistência à água, integração caixa-movimento), propriedades do titânio grau 5 (norma, densidade, módulo, escoamento, com fonte), o que cristais de safira de 0,20/0,30/0,45 mm implicam (deflexão sob pressão de dedo com a fórmula de placa mostrada, risco de fratura, por que 0,20 no centro e 0,30 na borda), parafusos spline (o que são, por que RM os usa), e como outros ultraplanos fixam cristal e movimento. Entregar `caixa/dossie.md`, `caixa/cristais.py` (cálculo de deflexão, stdlib), fontes.csv, claims.csv."""),
 ('U15','Seletor de função W/H: mecanismos análogos e máquina de estados','GPT-6 Pro',"""TAREFA — Estudar como a Richard Mille implementa seletores de função em outros modelos (RM 27-04, RM 67-02, calibres com "function selector" W/N/H) e como mecanismos análogos funcionam (clutch deslizante, roda de coroa, báscula, cames, detentes), a partir de fontes públicas e patentes; depois propor, como HIPÓTESE (E), uma ou duas máquinas de estados para o RM UP-01 (SELECTOR=W: comando → caminho de corda → barrilete; SELECTOR=H: comando → caminho de acerto → indicação), listando as peças mínimas necessárias em cada caminho e o que nas fotos públicas sustenta ou contradiz cada alternativa. Entregar `seletor/analogos.md`, `seletor/hipoteses.md` (H-SEL-001, 002 no formato: problema, hipótese, evidências a favor/contra, alternativas, teste discriminante), `seletor/estados.json`, fontes.csv, claims.csv."""),
 ('U16','Glossário trilíngue pt/en/fr da relojoaria ultraplana e do RM UP-01','GPT-5.6 Pro',"""TAREFA — Glossário de 120–160 termos (pt, en, fr) cobrindo: escape de alavanca e seus componentes, balanço/espiral/Kif, barrilete e corda, trem, motion works, platina/pontes, rubis e pivôs, cristais e caixa, seletor de função, termos de espessura e ultraplanos, classes de evidência do projeto, metrologia de imagem (homografia, landmark, overlay). Cada termo: definição de 1–3 frases para leigo, sinônimos, en, fr, e "no RM UP-01:" quando se aplicar. Entregar `glossario/glossario.md` e `glossario/glossario.json` (lista de objetos com os campos)."""),
 ('U17','Richard Mille, Renaud & Papi e a parceria Ferrari: história com fontes','GPT-5.6 Pro',"""TAREFA — Texto de estudo (não de hype) sobre: Richard Mille (a pessoa: formação, Mauboussin, fundação da marca em 2001), a marca (filosofia técnica, materiais, parcerias), Renaud & Papi / APRP / Audemars Piguet Le Locle (Giulio Papi, Dominique Renaud, papel no desenvolvimento de calibres para terceiros), e a parceria Richard Mille–Ferrari (início, modelos, o RM UP-01 como primeiro fruto). Entregar `historia-rm/texto.md` (3 000–4 500 palavras, com notas de rodapé para cada fato), `historia-rm/cronologia.csv`, fontes.csv. Marcar o que é fato documentado e o que é interpretação."""),
 ('U18','História dos ultraplanos: de 1946 ao RM UP-01','GPT-5.6 Pro',"""TAREFA — Linha do tempo comentada dos relógios e calibres ultraplanos: Audemars Piguet calibre 9ML/2003 (1946/1953), Piaget 9P (1957) e 12P (1960), Jean Lassale 1.2 (1976), Concord Delirium (1979) e a "guerra dos ultraplanos", Jaeger-LeCoultre 145/849, Vacheron 1003, o renascimento (Piaget Altiplano 900P 2014, AP RD#2/RD#3, Bulgari Octo Finissimo 2014–2022, Piaget AUC 2020), até o RM UP-01 (2022). Para cada marco: data, dimensões, solução técnica que permitiu a espessura, custo em robustez/reserva, fonte. Entregar `ultraplanos/linha-do-tempo.md`, `ultraplanos/marcos.csv`, fontes.csv."""),
 ('U19','Metrologia por imagem: método, checklist e script para calibrar fotos oficiais','GPT-6 Pro',"""TAREFA — Especificar e implementar (Python 3, só biblioteca padrão + opcionalmente numpy) o método de metrologia por imagem do projeto: escolha de âncoras no mesmo plano (ex.: largura do calibre 41,45 mm, diâmetros de cristal, cabeças dos 13 parafusos), correção de perspectiva por homografia a partir de 4+ pontos, conversão pixel → mm com propagação de incerteza, repetição em imagens independentes e cálculo de dispersão, métrica de erro de projeção para overlay CAD→foto, e contagem de dentes por periodicidade angular de borda. Entregar `metrologia/METODO.md` (passo a passo, armadilhas: lente, oblíqua, Z), `metrologia/homografia.py` (funções + exemplo com pontos sintéticos e teste), `metrologia/dentes.py` (contagem por periodicidade em um perfil de intensidade de exemplo), `metrologia/checklist.md`, fontes (bibliografia de visão computacional e fotogrametria com referências completas)."""),
 ('U20','Licenças e limites: o que um site de estudo pode publicar','GPT-5.6 Pro',"""TAREFA — Dossiê prático (não é parecer jurídico; dizer isso) sobre o que um site independente, educacional e não afiliado pode publicar sobre um relógio de marca: uso de marcas registradas em contexto descritivo, citação de fontes, reprodução de trechos, fotos oficiais e de imprensa (o que costuma ser licenciado para imprensa e o que não), patentes (domínio público do texto e figuras), renders próprios de um produto de terceiro, disclaimers recomendados, boas práticas de atribuição, riscos típicos (confusão, aproveitamento de imagem, uso comercial). Considerar Brasil, Suíça, UE e EUA em linhas gerais, com fontes públicas (leis, guias de escritórios de marcas, políticas de bases de patentes). Entregar `licencas/dossie.md`, `licencas/checklist-site.md`, `licencas/disclaimer-pt-en.md`, fontes.csv."""),
]
def kit(id_, titulo, modelo, tarefa, run_id=''):
    slug = re.sub(r'[^a-z0-9]+', '-', __import__('unicodedata').normalize('NFKD', titulo).encode('ascii','ignore').decode().lower()).strip('-')[:40]
    d = K / f'{id_}-{slug}'; d.mkdir(parents=True, exist_ok=True)
    prompt = f"PEDIDO {id_} — {titulo}\n\n{CTX}\n{tarefa}\n\nDevolva um único arquivo zip chamado {id_}-entrega.zip."
    if run_id:
        prompt += f"\n\nOnde estão os materiais de apoio (texto, pelo conector agenthub-tunnel): list_artifacts(run_id=\"{run_id}\") e get_artifact(artifact_id=..., max_chars=60000). CHARTER.md (convenções de IDs) e ESQUEMAS.md (colunas dos CSV). Se o conector não responder, diga isso em vez de improvisar."
    (d / 'BALCAO-prompt.txt').write_text(prompt, encoding='utf-8')
    (d / 'BALCAO-nota.txt').write_text(f"ANTES DE ENVIAR: nenhum anexo (materiais de texto pelo túnel). ENTREGA: salvar {id_}-entrega.zip em ~/repo/rmup01-digital-twin/_entrada/Balcao/", encoding='utf-8')
    (d / 'BALCAO-expectativa.txt').write_text(f"{id_}: zip com a estrutura pedida, LEIA-ME.md, fontes.csv e claims.csv; verificação: URLs conferidas, classes A–F coerentes, sem medida de desenho de patente; integra em research/ e docs/", encoding='utf-8')
    (d / 'BRIEF.md').write_text(f"# {id_} — {titulo}\n\nPedido ao ChatGPT web (Balcão, seção U). O enunciado autoritativo é o prompt no Balcão. Materiais de apoio neste run: CHARTER.md (convenções de IDs, ~4 kB) e ESQUEMAS.md (colunas dos CSV, ~2 kB), ambos texto, uma chamada cada. Volta: {id_}-entrega.zip em ~/repo/rmup01-digital-twin/_entrada/Balcao/.\n", encoding='utf-8')
    (d / 'PEDIDO.md').write_text(f"# {id_} — {titulo}\n\n1. No Balcão, abra o pedido {id_} e marque Rodei.\n2. Cole o prompt no ChatGPT ({modelo}).\n3. Salve a resposta como {id_}-entrega.zip em ~/repo/rmup01-digital-twin/_entrada/Balcao/.\n\n---\n\n{prompt}\n", encoding='utf-8')
    shutil.copy2(R / 'docs/PROJECT-CHARTER.md', d / 'CHARTER.md')
    (d / 'ESQUEMAS.md').write_text("# Esquemas dos CSV do projeto\n\nsource-manifest.csv: " + (R/'research/source-manifest.csv').read_text().splitlines()[0] + "\n\nclaims.csv: " + (R/'research/claims.csv').read_text().splitlines()[0] + "\n\nevidence-ledger.csv: " + (R/'evidence/evidence-ledger.csv').read_text().splitlines()[0] + "\n", encoding='utf-8')
    return d, prompt
def main(publicar):
    runs = json.loads((K/'HUB-RUNS.json').read_text()) if (K/'HUB-RUNS.json').exists() else {}
    for id_, titulo, modelo, tarefa in P:
        run_id = runs.get(id_, '')
        d, prompt = kit(id_, titulo, modelo, tarefa, run_id)
        if publicar and not run_id:
            r = subprocess.run(['agenthub','publish','--agent','claude','--project','rmup01','--status','running','--no-git','--json',
                '--title', f'{id_} — {titulo} (pedido ao ChatGPT web, Balcão seção U)',
                '--summary', f'Pedido {id_}: {titulo}; entrega em _entrada/Balcao/{id_}-entrega.zip',
                '--file', str(d/'BRIEF.md'), '--artifact', str(d/'CHARTER.md'), '--artifact', str(d/'ESQUEMAS.md')], text=True, capture_output=True)
            try:
                out = json.loads(r.stdout[r.stdout.index('{'):]); run_id = out.get('run_id') or out.get('id') or ''
            except Exception:
                run_id = ''
                print(id_, 'publish falhou:', (r.stderr or r.stdout)[:160].replace('\n',' '))
            if run_id:
                runs[id_] = run_id; (K/'HUB-RUNS.json').write_text(json.dumps(runs, indent=1))
                d, prompt = kit(id_, titulo, modelo, tarefa, run_id)
        print(id_, modelo, run_id or '(sem run)', d.name)
    (K/'PEDIDOS.json').write_text(json.dumps([dict(id=i,titulo=t,modelo=m,run_id=runs.get(i,'')) for i,t,m,_ in P], ensure_ascii=False, indent=1))
if __name__ == '__main__': main('--publicar' in sys.argv)
